# Generated by Django 5.1.6 on 2025-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('CR', 'Club Representative'), ('FC', 'Faculty Coordinator'), ('VFC', 'Venue Faculty Coordinator')], max_length=3),
        ),
    ]
