# Generated by Django 5.1.6 on 2025-03-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_permission_fc_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='fc_permission',
        ),
    ]
