# Generated by Django 5.1.6 on 2025-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_remove_permission_fc_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='fc_tag',
            field=models.CharField(default='no'),
        ),
    ]
