# Generated by Django 5.1.6 on 2025-03-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_permission_fc_tag'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='permission',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='venue.venue'),
        ),
    ]
