# Generated by Django 5.1.6 on 2025-03-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_remove_permission_venue_name_permission_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='venue',
            new_name='venue_name',
        ),
    ]
