# Generated by Django 5.1.6 on 2025-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_rename_venue_permission_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='vfc_tag',
            field=models.CharField(default='no'),
        ),
    ]
