# Generated by Django 5.1.6 on 2025-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_permission_vfc_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='date',
        ),
        migrations.AddField(
            model_name='permission',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
