# Generated by Django 5.1.6 on 2025-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_remove_permission_date_permission_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='scy_tag',
            field=models.CharField(default='no'),
        ),
    ]
