# Generated by Django 5.1.6 on 2025-03-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0010_permission_scy_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='event_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='event_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
