# Generated by Django 5.1.6 on 2025-03-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0012_alter_permission_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='off_tag',
            field=models.CharField(default='no'),
        ),
    ]
