# Generated by Django 5.1.6 on 2025-03-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('permissions', '0013_permission_off_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='fac_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Faculty.faculty'),
        ),
    ]
