# Generated by Django 5.1.6 on 2025-03-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('club', '0001_initial'),
        ('permissions', '0015_alter_permission_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='fac_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='club.clubs'),
        ),
    ]
