# Generated by Django 5.1.6 on 2025-03-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubreps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clubreps',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubrep', to='clubreps.clubs'),
        ),
    ]
