# Generated by Django 5.1.6 on 2025-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubreps', '0002_clubs_alter_clubreps_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubreps',
            name='club',
            field=models.CharField(),
        ),
    ]
