# Generated by Django 5.1.6 on 2025-03-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubreps', '0003_alter_clubreps_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubreps',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubrep', to='clubreps.clubs'),
        ),
    ]
