# Generated by Django 5.1.6 on 2025-03-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyCoordinator', '0005_alter_facultycoordinator_club'),
        ('club', '0001_initial'),
        ('clubreps', '0004_alter_clubreps_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubreps',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubrep', to='club.clubs'),
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
