# Generated by Django 5.1.6 on 2025-03-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubreps', '0005_alter_clubreps_club_delete_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreps',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
