# Generated by Django 5.1.6 on 2025-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubreps', '0006_clubreps_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreps',
            name='email',
            field=models.EmailField(default='hallify@gmail.com', max_length=254),
        ),
    ]
