# Generated by Django 5.1.6 on 2025-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0004_rename_secuirty_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='email',
            field=models.EmailField(default='hallify@gmail.com', max_length=254),
        ),
    ]
