# Generated by Django 5.1.6 on 2025-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('GN', 'General Venue'), ('DP', 'Department Venue'), ('CL', 'Class Room')], max_length=2, null=True),
        ),
    ]
