# Generated by Django 5.1.6 on 2025-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_venue_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('GN', 'General Venue'), ('DP', 'Department Venue'), ('CL', 'Class Room')], default='GN', max_length=2),
        ),
    ]
