# Generated by Django 5.1.6 on 2025-03-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Security',
        ),
    ]
