# Generated by Django 5.1.6 on 2025-03-06 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueFacultyCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venuefacultycoordinator_profile', to=settings.AUTH_USER_MODEL)),
                ('venue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venuefacultycoordinator', to='venue.venue')),
            ],
        ),
    ]
