# Generated by Django 5.1.6 on 2025-03-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyCoordinator', '0002_facultycoordinator_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycoordinator',
            name='club',
        ),
    ]
