# Generated by Django 5.1.6 on 2025-03-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyCoordinator', '0003_remove_facultycoordinator_club'),
        ('clubreps', '0004_alter_clubreps_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycoordinator',
            name='club',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facultycoordinator', to='clubreps.clubs'),
        ),
    ]
