# Generated by Django 5.1.6 on 2025-03-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyCoordinator', '0004_facultycoordinator_club'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycoordinator',
            name='club',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facultycoordinator', to='club.clubs'),
        ),
    ]
